apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
    </source>
    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch-service
      port 9200
      index kubernetes-logs
    </match>