version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.23.0
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"
    restart: always
