pipeline {
    agent none 

    environment {
        GIT_REPO_URL = 'https://jcardogo:$GITHUB_PAT@github.com/jcardogo/AlejandroCardoso_website.git'
    }

    stages {
        stage ('Clone Repository') {
            agent {label 'local'}
            steps {
                echo 'Starting Checkout stage'
                git clone ${env.GITHUB_REPO_URL}
            }
        }

        // stage ('Deploy Website - bash script') {
        //    agent {label 'local'}
        //    steps {
        //        script {
        //            sh './docker_webserver_no_context.sh'
        //        }
        //    }
        // }
    }
}