pipeline {
    agent none

    parameters {
        string(name: 'REPO_URL', defaultValue: 'github.com/jcardogo/AlejandroCardoso_website.git', description: 'Git repository URL')
    }

    stages {
        // stage('Create Directory'){
        //     agent { label 'local' }
        //     steps {
        //         script {
        //             sh 'mkdir -p $WORKSPACE/website_content'
        //         }
        //     }
        // }

        // stage('Clone Repository') {
        //     agent { label 'local' }
        //     steps {
        //         withCredentials([usernamePassword(credentialsId: 'Github_PAT', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_PWD')]) {
        //             git url: "https://${GITHUB_USER}:${GITHUB_PWD}@${params.REPO_URL}"
        //         }
        //     }
        // }

        stage('Dockerize Nginx'){
            agent { label 'local' }
            steps {
                script {
                    sh '''
                        echo "FROM nginx:alpine" > Dockerfile
                        echo "COPY $WORKSPACE/website_content /usr/share/nginx/html/" 
                        docker build -t my-ngonx-image -f Dockerfile .
                        docker run -d -p 8086:80 --name my-nginx-container my-nginx-image
                    '''
                }
            }   
        }
    }
}