import os
def create_python_script(filename):
  comments = "# This is the first file generated by script that I create and I'm so happy to see how it works"
  with open(filename, "w") as file:
    file.write(comments)
  filesize = os.path.getsize(filename)
  return(filesize)

print(create_python_script("program.py"))